language: generic
os: osx

matrix:
  include:
    - os: osx
      osx_image: xcode8

install:
  - if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
  - git clone https://github.com/hioa-cs/IncludeOS.git
  - cd IncludeOS
  - git checkout dev
  - git submodule update --init --recursive
  
before_script:
  - cd test
  - mkdir darwin && cd darwin
  
script:
  - cmake ..
  - make && ./unittests